using System.Text.Json;
using Deskribe.Sdk;
using Deskribe.Sdk.Models;

namespace Deskribe.Plugins.Backend.Terraform;

public class TerraformProvisioner : IProvisioner
{
    public string Name => "terraform";

    public Task<ProvisionResult> ApplyAsync(DeskribePlan plan, CancellationToken ct)
    {
        // Terraform provisioner generates artifacts then runs terraform apply
        // For now, we produce planned outputs (actual TF execution would be external)
        var outputs = new Dictionary<string, Dictionary<string, string>>();

        foreach (var rp in plan.ResourcePlans)
        {
            outputs[rp.ResourceType] = rp.PlannedOutputs;
        }

        Console.WriteLine($"[Terraform] Planned {plan.ResourcePlans.Count} resources for {plan.AppName}-{plan.Environment}");

        return Task.FromResult(new ProvisionResult
        {
            Success = true,
            ResourceOutputs = outputs
        });
    }

    public Task<ArtifactResult> GenerateArtifactsAsync(DeskribePlan plan, string outputDir, CancellationToken ct)
    {
        var files = new List<GeneratedFile>();

        // Generate terraform.tfvars.json
        var tfvars = new Dictionary<string, object?>
        {
            ["app_name"] = plan.AppName,
            ["environment"] = plan.Environment,
            ["region"] = plan.Platform.Defaults.Region ?? "westeurope"
        };

        foreach (var rp in plan.ResourcePlans)
        {
            var resourceKey = rp.ResourceType.Replace(".", "_");
            tfvars[$"{resourceKey}_config"] = rp.Configuration;
        }

        files.Add(new GeneratedFile
        {
            Path = Path.Combine(outputDir, "terraform.tfvars.json"),
            Content = JsonSerializer.Serialize(tfvars, new JsonSerializerOptions { WriteIndented = true }),
            Format = "json"
        });

        // Generate helm-values.yaml for workload
        if (plan.Workload is not null)
        {
            var helmValues = GenerateHelmValues(plan);
            files.Add(new GeneratedFile
            {
                Path = Path.Combine(outputDir, "helm-values.yaml"),
                Content = helmValues,
                Format = "yaml"
            });
        }

        // Generate bindings.json
        var bindings = new Dictionary<string, Dictionary<string, string>>();
        foreach (var rp in plan.ResourcePlans)
        {
            bindings[rp.ResourceType] = rp.PlannedOutputs;
        }

        files.Add(new GeneratedFile
        {
            Path = Path.Combine(outputDir, "bindings.json"),
            Content = JsonSerializer.Serialize(bindings, new JsonSerializerOptions { WriteIndented = true }),
            Format = "json"
        });

        return Task.FromResult(new ArtifactResult
        {
            Success = true,
            Files = files
        });
    }

    public Task DestroyAsync(string appName, string environment, PlatformConfig platform, CancellationToken ct)
    {
        Console.WriteLine($"[Terraform] Destroy for {appName}-{environment} would run: terraform destroy");
        return Task.CompletedTask;
    }

    private static string GenerateHelmValues(DeskribePlan plan)
    {
        var w = plan.Workload!;
        var lines = new List<string>
        {
            $"# Generated by Deskribe for {plan.AppName} ({plan.Environment})",
            $"replicaCount: {w.Replicas}",
            $"image:",
            $"  repository: {(w.Image?.Split(':')[0] ?? "nginx")}",
            $"  tag: \"{(w.Image?.Split(':').ElementAtOrDefault(1) ?? "latest")}\"",
            $"resources:",
            $"  requests:",
            $"    cpu: \"{w.Cpu}\"",
            $"    memory: \"{w.Memory}\"",
            $"  limits:",
            $"    cpu: \"{w.Cpu}\"",
            $"    memory: \"{w.Memory}\""
        };

        if (w.EnvironmentVariables.Count > 0)
        {
            lines.Add("env:");
            foreach (var (key, value) in w.EnvironmentVariables)
            {
                lines.Add($"  {key}: \"{value}\"");
            }
        }

        return string.Join("\n", lines) + "\n";
    }
}
