// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeatherApi;

#nullable disable

namespace WeatherApi.Migrations;

[DbContext(typeof(WeatherDb))]
partial class WeatherDbModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.3")
            .HasAnnotation("Relational:MaxIdentifierLength", 63)
            .UseIdentityByDefaultColumns();

        modelBuilder.Entity("WeatherApi.WeatherRecord", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

            b.Property<string>("City")
                .IsRequired()
                .HasColumnType("text");

            b.Property<string>("Summary")
                .HasColumnType("text");

            b.Property<int>("TemperatureC")
                .HasColumnType("integer");

            b.HasKey("Id");

            b.ToTable("WeatherRecords");

            b.HasData(
                new { Id = 1, City = "London", TemperatureC = 12, Summary = "Cloudy" },
                new { Id = 2, City = "Amsterdam", TemperatureC = 15, Summary = "Partly sunny" },
                new { Id = 3, City = "Lisbon", TemperatureC = 24, Summary = "Warm" },
                new { Id = 4, City = "Berlin", TemperatureC = 9, Summary = "Cold" },
                new { Id = 5, City = "Paris", TemperatureC = 17, Summary = "Mild" }
            );
        });
    }
}
